const actionTypes = {
	USER_FETCH_REQUESTED: 'USER_FETCH_REQUESTED',
	USER_FETCH_FAILED: 'USER_FETCH_FAILED',
	USER_FETCH_SUCCEEDED: 'USER_FETCH_SUCCEEDED',

	USER_SEARCH_REQUESTED: 'USER_SEARCH_REQUESTED',
	USER_SEARCH_FAILED: 'USER_SEARCH_FAILED',
	USER_SEARCH_SUCCEEDED: 'USER_SEARCH_SUCCEEDED',


	USER_VALIDATION_REQUESTED: 'USER_VALIDATION_REQUESTED',
	USER_VALIDATION_FAILED: 'USER_VALIDATION_FAILED',
	USER_VALIDATION_SUCCEEDED: 'USER_VALIDATION_SUCCEEDED',

	USER_LOGOUT_REQUESTED: 'USER_LOGOUT_REQUESTED',
	USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED',
	USER_LOGOUT_SUCCEEDED: 'USER_LOGOUT_SUCCEEDED',
	USER_LOGIN_FORM_REQUESTED: 'USER_LOGIN_FORM_REQUESTED',
	USER_LOGIN_FORM_SHOW: 'USER_LOGIN_FORM_SHOW',

	USER_FETCH_BY_ID_REQUESTED: 'USER_FETCH_BY_ID_REQUESTED',
	USER_FETCH_BY_ID_SUCCEEDED: 'USER_FETCH_BY_ID_SUCCEEDED',
	USER_FETCH_BY_ID_FAILED: 'USER_FETCH_BY_ID_FAILED',
};

export default actionTypes;
