const actionTypes = {
	USER_FETCH_REQUESTED: 'USER_FETCH_REQUESTED',
	USER_FETCH_FAILED: 'USER_FETCH_FAILED',
	USER_FETCH_SUCCEEDED: 'USER_FETCH_SUCCEEDED',
	USER_SEARCH_REQUESTED: 'USER_SEARCH_REQUESTED',
	USER_SEARCH_FAILED: 'USER_SEARCH_FAILED',
	USER_SEARCH_SUCCEEDED: 'USER_SEARCH_SUCCEEDED',
	USER_VALIDATION_REQUESTED: 'USER_VALIDATION_REQUESTED',
	USER_VALIDATION_FAILED: 'USER_VALIDATION_FAILED',
	USER_VALIDATION_SUCCEEDED: 'USER_VALIDATION_SUCCEEDED',
};

export default actionTypes;
